### ISSUE TITLE
Liste des terms RST

### ISSUE THREAD

**Issue by Seluj78** [vpoulailleau/padpo#1]
https://github.com/vpoulailleau/padpo/blob/82604c068cf57b398dec048c8e37484081b2086c/padpo.py#L83

Est tu sur que cette liste est complète ?

**Comment by vpoulailleau** [comment]
Non, je ne suis pas sûr. Je l'ai construit par expérience. Sais-tu où je pourrais trouver la liste complète ?

**Comment by Seluj78** [comment]
J'invoque @JulienPalard

**Comment by awecx** [comment]
Les hyperliens ne passent pas non plus. Ils n'ont pas de balise et « ``» sont interprétés comme des guillemets au passage.

**Comment by vpoulailleau** [comment]
Merci, je prends note.

**Comment by JulienPalard** [comment]
Pour la liste des termes, c'est compliqué en rst puisqu'on peut en ajouter.

Tu peux peut être t'inspirer de ce qu'on fait dans [pospell](https://github.com/JulienPalard/pospell/blob/master/pospell.py#L104), ça tire une grosse dépendance mais ça t'assure que c'est juste.

Sinon une regex comme :

     :[a-z:]+:`.+?`

couvre pas trop mal les cas, entre les `` quasiment tout est autorisé (j'ignore si backslash backtick est autorisé ...), je viens de la tester sur la doc de Python, elle me semble OK.

**Comment by vpoulailleau** [comment]
@JulienPalard Je suis partisan d'utiliser ta regex car elle est simple à comprendre et n'a pas la dépendance à docutils (mais la dépendance à docutils est effectivement la solution à coup sur). Quitte ensuite à gérer au cas par cas les exceptions à cette regex…
