### ISSUE TITLE
Could -i accept multiple files?

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/padpo#11]
Would be nice in a CI also, like:
`padpo -i *.po`

**Comment by vpoulailleau** [comment]
Not yet. Though, you can pass a directory instead of a file. Only `.po` files inside the directory are checked.

@JulienPalard : is it sufficient?

**Comment by vpoulailleau** [comment]
BTW, I've implemented locally a prototype in ten lines of code, so if it's necessary, I can commit it. @JulienPalard @Seluj78 what do you think?

**Comment by Seluj78** [comment]
Sure why not ? 

Does your folder search searches recursively ?

**Comment by JulienPalard** [comment]
> Not yet. Though, you can pass a directory instead of a file. Only `.po` files inside the directory are checked.
> 
> @JulienPalard : is it sufficient?

No, for python-docs-fr I'd like to tell explicitly what file to check what file to skip. Something like this https://github.com/JulienPalard/python-docs-fr/commit/be51effc8d307f674c92ac1733bdd5bbd9f3b7f5

**Comment by vpoulailleau** [comment]
> Does your folder search searches recursively ?

Yes, here: https://github.com/vpoulailleau/padpo/blob/9ba93c8d6518d0a86b997c023c3e1927a16f999f/padpo/padpo.py#L32

**Comment by vpoulailleau** [comment]
> No, for python-docs-fr I'd like to tell explicitly what file to check what file to skip. Something like this [JulienPalard/python-docs-fr@be51eff](https://github.com/JulienPalard/python-docs-fr/commit/be51effc8d307f674c92ac1733bdd5bbd9f3b7f5)

OK, I'll push the prototype.

**Comment by JulienPalard** [comment]
Thanks!!! Trying it right now, like `padpo *.po */*.po` in my clone of python-docs-fr :]

**Comment by vpoulailleau** [comment]
> Thanks!!! Trying it right now, like `padpo *.po */*.po` in my clone of python-docs-fr :]

This is an optional named argument, you have to name it.

`padpo -i *.po */*.po` or `padpo --input-path *.po */*.po`

**Comment by JulienPalard** [comment]
Oh that's what I meant and what I typed on my shell :] thanks for noticing though.
