### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by vpoulailleau** [vpoulailleau/padpo#17]
`<NBSP>:<space>::` is OK but padpo tells some problem about NBSP

**Comment by JulienPalard** [comment]
Beware, `<space>::` is valid, even mandatory, when prefixed by a dot, see 41d0079abcccfbf12461f8734f5158082a6a559a in python-docs-fr.

Because `blah blah.<NBSP>::` is rendered as `blah blah. :`.

**Comment by vpoulailleau** [comment]
Yes you're right! As well after a `?` or a `!`. 

@JulienPalard Do you see any other mandatory cases?

**Comment by JulienPalard** [comment]
Not at this time.

**Comment by vpoulailleau** [comment]
@JulienPalard OK, thanks!
