### ISSUE TITLE
Pinning setuptools as a dependency

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/padpo#19]
This does not looks like a good idea, and it's wrong: setuptools is not a runtime dependency of your project, just a dependency of your build system.

It's also not nice as it could conflict with pip itself.

**Comment by vpoulailleau** [comment]
Well, to my knowledge, it is a runtime dependency, to install grammalecte at runtime (no package for grammalecte on PyPI). That was suggested by somebody, I don't remember who. I have to check wether I can remove the dependency.

I don't have the time right now (at least till end of february), but I keep the issue in mind.

**Comment by vpoulailleau** [comment]
I've just created [`pygrammalecte`](https://github.com/vpoulailleau/pygrammalecte) that solves this, and allows to easily use/install Grammalecte with Python.

The new (in progress) version of `padpo` uses `pygrammalecte` and doesn't require `setuptools`.
