### ISSUE TITLE
Packaging for PyPI

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/padpo#4]
Any idea why grammalecte is not on PyPI? it would be nice so we can package padpo with grammalecte as an install dependency.

**Comment by vpoulailleau** [comment]
Based on #5 of @Seluj78, padpo is now on PyPI. You may have a try and give feedback.

For grammalecte, I have no idea. It is not developed with git but with fossil.

I talked to @pofilo who created a mirror of grammalecte on GitHub, we don't have yet an easy solution to get a tagged version of grammalecte-cli in GitHub (which could then be a dependency in the requirements.txt). I don't know why grammalecte is not on PyPI, and, to ask the creator, one has to create an account on the grammalecte fossil (I didn't do that).

I've just uploaded padpo 0.2.0 on PyPI that tries to install automatically grammalecte on first padpo usage.

**Comment by JulienPalard** [comment]
Nice to hear! Thanks!
